name: dividend_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+10

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.67.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^29.1.0
  http: ^1.3.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production

flutter_icons:
  ios: true
  image_path: "assets/icon/app_icon.png"
